# -*- coding: utf-8 -*-
"""GradioWC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsmdU-hXCkzvLCaAA3cWB6OrhSQUoYhM
"""

#pip install gradio

#pip install stylecloud

#pip install --upgrade pillow

def create_wordcloud(file, language, icon):
    try:
        # Metin dosyasını oku
        text = file.decode("utf-8")
        if not text.strip():
            raise ValueError("Metin dosyası boş.")

        # İkon seçimi için maske yükle
        icon_paths = {
            "fas fa-car": "/content/car.png",
            "fas fa-star-and-crescent": "/content/star_and_crescent.png",
            "fas fa-trophy": "/content/trophy.png",
            "fas fa-heart": "/content/heart.png"
        }
        mask_path = icon_paths.get(icon, None)
        if mask_path and os.path.exists(mask_path):
            mask = np.array(Image.open(mask_path))
        else:
            mask = None  # Maske yoksa varsayılan şekil

        # Kelime bulutu oluştur
        wordcloud = WordCloud(width=800, height=400, background_color="white", mask=mask).generate(text)
        wordcloud.to_file("wordcloud.png")  # Çıktıyı kaydet

        return "wordcloud.png"
    except Exception as e:
        print(f"Hata: {str(e)}")
        return str(e)
# Gradio arayüzü oluştur
with gr.Blocks() as demo:
    gr.Markdown('### Kelime Bulut Oluşturucu')
    with gr.Row():
        file_input = gr.File(label="Metin Dosyası", type="binary")
        language = gr.Radio(choices=['TR', 'EN'], label='Dil Seçimi', value='TR')
        icon = gr.Dropdown(choices=["fas fa-car", "fas fa-star-and-crescent", "fas fa-trophy", "fas fa-heart"],
                           label='İkon Seçiniz', value='fas fa-car')
        output_file = gr.File(label='Kelime Bulutunu İndir')
        create_button = gr.Button('Oluştur')

    create_button.click(
        create_wordcloud,
        inputs=[file_input, language, icon],
        outputs=output_file
    )

demo.launch(share=True, debug=True)

